/* Auto-generated by genmsg_cpp for file /home/joren/ros/laser_to_wall/msg/WallScan.msg */
#ifndef LASER_TO_WALL_MESSAGE_WALLSCAN_H
#define LASER_TO_WALL_MESSAGE_WALLSCAN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace laser_to_wall
{
template <class ContainerAllocator>
struct WallScan_ {
  typedef WallScan_<ContainerAllocator> Type;

  WallScan_()
  : header()
  , wall_left(false)
  , wall_right(false)
  , wall_front(false)
  {
  }

  WallScan_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , wall_left(false)
  , wall_right(false)
  , wall_front(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _wall_left_type;
  uint8_t wall_left;

  typedef uint8_t _wall_right_type;
  uint8_t wall_right;

  typedef uint8_t _wall_front_type;
  uint8_t wall_front;


  typedef boost::shared_ptr< ::laser_to_wall::WallScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_to_wall::WallScan_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WallScan
typedef  ::laser_to_wall::WallScan_<std::allocator<void> > WallScan;

typedef boost::shared_ptr< ::laser_to_wall::WallScan> WallScanPtr;
typedef boost::shared_ptr< ::laser_to_wall::WallScan const> WallScanConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::laser_to_wall::WallScan_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::laser_to_wall::WallScan_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace laser_to_wall

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::laser_to_wall::WallScan_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::laser_to_wall::WallScan_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::laser_to_wall::WallScan_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3eac0369e6437026a45b36a926ada13";
  }

  static const char* value(const  ::laser_to_wall::WallScan_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb3eac0369e643702ULL;
  static const uint64_t static_value2 = 0x6a45b36a926ada13ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_to_wall::WallScan_<ContainerAllocator> > {
  static const char* value() 
  {
    return "laser_to_wall/WallScan";
  }

  static const char* value(const  ::laser_to_wall::WallScan_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::laser_to_wall::WallScan_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool wall_left\n\
bool wall_right\n\
bool wall_front\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::laser_to_wall::WallScan_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::laser_to_wall::WallScan_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::laser_to_wall::WallScan_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::laser_to_wall::WallScan_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.wall_left);
    stream.next(m.wall_right);
    stream.next(m.wall_front);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WallScan_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_to_wall::WallScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::laser_to_wall::WallScan_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wall_left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wall_left);
    s << indent << "wall_right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wall_right);
    s << indent << "wall_front: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wall_front);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LASER_TO_WALL_MESSAGE_WALLSCAN_H

